apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cnt-app
  namespace: dev
spec:
  replicas: 3
  
  selector:
     matchLabels:
        app: cnt-app
  minReadySeconds: 10
  strategy:
     type: RollingUpdate # rolling update (kill one, bring one up  means don't kill them at the same time) / create
     rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
  template:
    metadata:
      labels:
        app: cnt-app
    spec:
      containers:
      - name: cnt-app
        image: 520394173897.dkr.ecr.us-east-1.amazonaws.com/devop_repository:0.0.5-RELEASE
        ports:
        - containerPort: 80 